/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//package specificheat;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;


/**
 *
 * @author Kyle Cancio
 */
public class Problem2 extends javax.swing.JFrame {

    /**
     * Creates new form Problem1
     */
    public Problem2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        solveB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SolutionField = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        givenField = new javax.swing.JTextPane();
        answerField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        q1Text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        q2Text = new javax.swing.JTextField();
        dText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        clearB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Word Problem 2: Coulomb's Law");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                openMenu(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Klavika Regular", 0, 18)); // NOI18N
        jLabel1.setText("Word Problem 2: Coulomb’s Law");

        solveB.setText("SOLVE!");
        solveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveBActionPerformed(evt);
            }
        });

        SolutionField.setContentType("text/html"); // NOI18N
        SolutionField.setText("<b>SOLUTION</b>");
        jScrollPane1.setViewportView(SolutionField);

        givenField.setEditable(false);
        givenField.setContentType("text/html"); // NOI18N
        givenField.setText("<b>GIVEN:</b>"
            + "<br>"
            + "q1: "
            + "<br>"
            + "q2: "
            + "<br>"
            + "r: "
            + "<br>"
            + "<b>REQUIRED:</b>"
            + "<br>"
            + "Fe?"
            + "<br>"
            + "<b>EQUATION:</b>"
            + "Fe = kq1q2 / r"
            + "<br>"
            + "where k = 9x10^9 N-m<sup>2</sup>");
        jScrollPane2.setViewportView(givenField);

        answerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerFieldActionPerformed(evt);
            }
        });
        answerField.setText("ANSWER: ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("A charge of");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("<html>&#181;C is</html>");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("m from another charge of");

        dText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dTextActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("<html>&#181;C.</html>");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Calculate the force between the charges. ");

        clearB.setText("CLEAR");
        clearB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(answerField)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(255, 255, 255)
                                        .addComponent(clearB, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(solveB, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(q1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(q2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(q1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(q2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(solveB)
                    .addComponent(clearB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answerField)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    double kval = 9.0E9;
    
    private void checkVals(String q1, String q2, String r) throws NoNegativeValue{
        double q1p = 0.0, q2p = 0.0, rp = 0.0;
        q1p = Double.parseDouble(q1)/1000000;
        q2p = Double.parseDouble(q2)/1000000;
        rp = Double.parseDouble(r);
        
        if(rp <= 0){
            throw new NoNegativeValue();
        }else{
        
        String force = null;
                
        if(q1p < 0 && q2p < 0){
            force = "Repulsive";
            q1p = Math.abs(q1p);
            q2p = Math.abs(q2p);
        }else if(q1p < 0 && q2p > 0){
            force = "Attractive";
            q1p = Math.abs(q1p);
        }else if(q1p > 0 && q2p < 0){
            force = "Attractive";
            q2p = Math.abs(q2p);
        }else{
            force = "Repulsive";
        }
        
        String x = null;
                try {
                   x =  givenField.getDocument().getText(0, givenField.getDocument().getLength()) ;
                } catch (BadLocationException ex) {
                    Logger.getLogger(SpecificHeatGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                givenField.setText("<b>GIVEN:</b>"
                + "<br>"
                + "q1: " + q1 + "&#181;C = " + q1 + "x10<sup>-6</sup>C"
                + "<br>"
                + "q2: " + q2 + "&#181;C = " + q2 + "x10<sup>-6</sup>C"
                + "<br>"
                + "r: " + r + "m"
                + "<br>"
                + "<b>REQUIRED:</b>"
                + "<br>"
                + "Fe?"
                + "<br>"
                + "<b>EQUATION:</b>"
                + "Fe = kq1q2 / r"
                + "<br>"
                + "where k = 9x10^9 N-m<sup>2</sup>");
                
                String finalAns = String.valueOf(solveC(q1p, q2p, rp));
                
                x = null;

                try {
                   x =  SolutionField.getDocument().getText(0, SolutionField.getDocument().getLength()) ;
                } catch (BadLocationException ex) {
                    Logger.getLogger(SpecificHeatGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                SolutionField.setText("<b>SOLUTION:</b>"
                + "<br>"
                + "Fe =  (9x10<sup>9</sup>)(" + String.valueOf(Math.abs(Double.parseDouble(q1))) + "x10<sup>-6</sup>C)(" + String.valueOf(Math.abs(Double.parseDouble(q2))) + "x10<sup>-6</sup>C)) / (" + String.valueOf(rp) + "m)<sup>2</sup>"
                + "<br>"
                + "Fe = <b>" + finalAns + "</b> N," + force);
                
                answerField.setText("ANSWER: " + finalAns + " N," + force);
                
        }
    }
    
    private double solveC(Double q1, Double q2, Double r){
        double retVal = 0.0;
        
        retVal = (double)Math.round(((kval * q1 * q2) / (r * r))*1000)/1000;
        
        return retVal;
    }
    
    private void solveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveBActionPerformed
        try{
            checkVals(q1Text.getText(),q2Text.getText(),dText.getText());
        }
        catch(NoNegativeValue nnv){
                JOptionPane.showMessageDialog(null, "Distance between the charges cannot be negative or zero", "Warning", JOptionPane.ERROR_MESSAGE);
        }
        catch(NumberFormatException nfe){
            if(q1Text.equals("") || q2Text.equals("") || dText.equals("")){
                JOptionPane.showMessageDialog(null, "Fields cannot be left blank", "Warning", JOptionPane.ERROR_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Invalid Input", "Warning", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_solveBActionPerformed

    private void answerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerFieldActionPerformed

    private void dTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dTextActionPerformed

    private void clearBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBActionPerformed
        q1Text.setText("");
        q2Text.setText("");
        dText.setText("");
        givenField.setText("<b>GIVEN:</b>"
        + "<br>"
        + "q1: "
        + "<br>"
        + "q2: "
        + "<br>"
        + "r: "
        + "<br>"
        + "<b>REQUIRED:</b>"
        + "<br>"
        + "Fe?"
        + "<br>"
        + "<b>EQUATION:</b>"
        + "Fe = kq1q2 / r"
        + "<br>"
        + "where k = 9x10^9 N-m<sup>2</sup>");
        SolutionField.setText("<b>SOLUTION</b>");
        answerField.setText("ANSWER: ");
        
    }//GEN-LAST:event_clearBActionPerformed

    private void openMenu(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_openMenu
        new MenuSelector().setVisible(true);
        evt.getWindow().dispose();
    }//GEN-LAST:event_openMenu

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Problem2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Problem2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Problem2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Problem2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Problem2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane SolutionField;
    private javax.swing.JTextField answerField;
    private javax.swing.JButton clearB;
    private javax.swing.JTextField dText;
    private javax.swing.JTextPane givenField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField q1Text;
    private javax.swing.JTextField q2Text;
    private javax.swing.JButton solveB;
    // End of variables declaration//GEN-END:variables
}

